services:
  postgres:
    image: postgres:16
    container_name: expense_bot_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: expense_user
      POSTGRES_PASSWORD: expense_pass
      POSTGRES_DB: expense_bot
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: